# Generated by Django 2.2.19 on 2022-06-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenandchatid',
            name='token',
            field=models.CharField(max_length=200),
        ),
    ]
