# Generated by Django 2.2.19 on 2022-06-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220619_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenandchatid',
            name='chat_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tokenandchatid',
            name='token',
            field=models.TextField(),
        ),
    ]
