# Generated by Django 2.2.19 on 2022-06-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220619_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpAddres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='TokenAndChatId',
        ),
    ]
