# Generated by Django 2.2.19 on 2022-06-19 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20220619_2112'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IpAddres',
            new_name='UserIp',
        ),
    ]
