# Generated by Django 2.2.19 on 2022-06-19 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20220619_2201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userip',
            old_name='ip',
            new_name='IpUser',
        ),
    ]
