# Generated by Django 2.2.19 on 2022-06-19 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20220619_2210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userip',
            old_name='IpUser',
            new_name='Ip',
        ),
    ]
